package lk.icbt.dentalclinic.model.scheduling;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lk.icbt.dentalclinic.model.billing.Bill;
import lk.icbt.dentalclinic.model.identity.Dentist;
import lk.icbt.dentalclinic.model.identity.Patient;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Objects;

/**
 * A single visit, identified by the appointment number the brief requires.
 *
 * <p>The unique constraint on {@code (dentist_id, appointment_date, appointment_time)} is
 * declared here as well as in the migration so that the mapping documents it — it is the
 * constraint that structurally removes the clinic's double-booking problem
 * (<strong>assumption A11</strong>). The service layer also checks availability, but only to
 * produce a helpful message; this is what makes the clash impossible under a race.
 */
@Entity
@Table(name = "appointments",
       uniqueConstraints = @UniqueConstraint(
               name = "uq_dentist_slot",
               columnNames = {"dentist_id", "appointment_date", "appointment_time", "slot_lock"}))
public class Appointment {

    private static final String SLOT_HELD = "A";

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Format {@code APT-<year>-<0000>}; generated by the service layer in M4. */
    @Column(name = "appointment_no", nullable = false, unique = true, length = 20)
    private String appointmentNo;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "patient_id", nullable = false)
    private Patient patient;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "dentist_id", nullable = false)
    private Dentist dentist;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "treatment_id", nullable = false)
    private Treatment treatment;

    /**
     * {@code Appointment "1" --> "0..1" Bill}. Navigable from the appointment, matching the
     * class diagram; the unique index on {@code bill_id} enforces the {@code 0..1}.
     */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bill_id", unique = true)
    private Bill bill;

    @Column(name = "appointment_date", nullable = false)
    private LocalDate appointmentDate;

    @Column(name = "appointment_time", nullable = false)
    private LocalTime appointmentTime;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private AppointmentStatus status = AppointmentStatus.SCHEDULED;

    @Column(name = "reason_for_visit", length = 255)
    private String reasonForVisit;

    @Column(name = "clinical_notes", length = 1000)
    private String clinicalNotes;

    @Column(name = "cancellation_reason", length = 255)
    private String cancellationReason;

    @Column(name = "created_by", nullable = false, length = 50)
    private String createdBy;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    /**
     * Occupancy marker participating in {@code uq_dentist_slot}: {@code "A"} while this
     * appointment holds its slot, {@code null} once cancelled.
     *
     * <p>Both engines treat NULLs in a unique index as distinct, so a cancelled appointment
     * stops competing for its slot and the slot becomes rebookable, while two live bookings
     * still collide. Derived from {@link #status} by {@link #syncSlotLock()} rather than set
     * by callers, so the two cannot drift apart.
     */
    @Column(name = "slot_lock", length = 1)
    private String slotLock = SLOT_HELD;

    protected Appointment() {
        // required by JPA
    }

    public Appointment(String appointmentNo, Patient patient, Dentist dentist,
                       Treatment treatment, LocalDate appointmentDate,
                       LocalTime appointmentTime, String createdBy) {
        this.appointmentNo = appointmentNo;
        this.patient = patient;
        this.dentist = dentist;
        this.treatment = treatment;
        this.appointmentDate = appointmentDate;
        this.appointmentTime = appointmentTime;
        this.createdBy = createdBy;
    }

    // ---------------------------------------------------------------- behaviour ---

    public LocalDateTime getScheduledAt() {
        return LocalDateTime.of(appointmentDate, appointmentTime);
    }

    public boolean isInThePast() {
        return getScheduledAt().isBefore(LocalDateTime.now());
    }

    /**
     * Whether two appointments compete for the same dentist and slot.
     *
     * <p>Cancelled appointments never clash: a cancelled slot is free. This mirrors what the
     * unique index can express, so the in-memory check and the database agree.
     */
    public boolean clashesWith(Appointment other) {
        if (other == null || other == this) {
            return false;
        }
        if (status == AppointmentStatus.CANCELLED || other.status == AppointmentStatus.CANCELLED) {
            return false;
        }
        return Objects.equals(dentist, other.dentist)
                && Objects.equals(appointmentDate, other.appointmentDate)
                && Objects.equals(appointmentTime, other.appointmentTime);
    }

    /** Whether a bill may be raised. Only completed treatment is billable. */
    public boolean isBillable() {
        return status == AppointmentStatus.COMPLETED;
    }

    public void reschedule(LocalDate date, LocalTime time) {
        if (date == null || time == null) {
            throw new IllegalArgumentException("Date and time are required");
        }
        if (status.isTerminal()) {
            throw new IllegalStateException(
                    "A " + status + " appointment cannot be rescheduled");
        }
        this.appointmentDate = date;
        this.appointmentTime = time;
    }

    public void cancel(String reason) {
        assertTransitionAllowed(AppointmentStatus.CANCELLED);
        this.status = AppointmentStatus.CANCELLED;
        this.cancellationReason = reason;
    }

    public void confirm() {
        assertTransitionAllowed(AppointmentStatus.CONFIRMED);
        this.status = AppointmentStatus.CONFIRMED;
    }

    public void complete(String notes) {
        assertTransitionAllowed(AppointmentStatus.COMPLETED);
        this.status = AppointmentStatus.COMPLETED;
        this.clinicalNotes = notes;
    }

    public void markNoShow() {
        assertTransitionAllowed(AppointmentStatus.NO_SHOW);
        this.status = AppointmentStatus.NO_SHOW;
    }

    /**
     * Keeps {@code slotLock} consistent with {@code status} on every write, so the unique
     * slot index frees a slot the moment its appointment is cancelled.
     */
    @PrePersist
    @PreUpdate
    private void syncSlotLock() {
        this.slotLock = (status == AppointmentStatus.CANCELLED) ? null : SLOT_HELD;
    }

    /**
     * Guards every state change against the transition table on
     * {@link AppointmentStatus}, so an illegal move fails here rather than leaving the
     * record in a state no one designed for.
     */
    private void assertTransitionAllowed(AppointmentStatus target) {
        if (!status.canTransitionTo(target)) {
            throw new IllegalStateException(
                    "Cannot move appointment from " + status + " to " + target);
        }
    }

    // ------------------------------------------------------------------ accessors ---

    public Long getId() {
        return id;
    }

    public String getAppointmentNo() {
        return appointmentNo;
    }

    public Patient getPatient() {
        return patient;
    }

    /** Package-visible to callers going through {@link Patient#addAppointment}. */
    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    public Dentist getDentist() {
        return dentist;
    }

    public void setDentist(Dentist dentist) {
        this.dentist = dentist;
    }

    public Treatment getTreatment() {
        return treatment;
    }

    public void setTreatment(Treatment treatment) {
        this.treatment = treatment;
    }

    public Bill getBill() {
        return bill;
    }

    public void setBill(Bill bill) {
        this.bill = bill;
    }

    public LocalDate getAppointmentDate() {
        return appointmentDate;
    }

    public LocalTime getAppointmentTime() {
        return appointmentTime;
    }

    public AppointmentStatus getStatus() {
        return status;
    }

    public String getReasonForVisit() {
        return reasonForVisit;
    }

    public void setReasonForVisit(String reasonForVisit) {
        this.reasonForVisit = reasonForVisit;
    }

    public String getClinicalNotes() {
        return clinicalNotes;
    }

    public String getCancellationReason() {
        return cancellationReason;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /** Visible for tests asserting that cancellation releases the slot. */
    public String getSlotLock() {
        return slotLock;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof Appointment appointment)) {
            return false;
        }
        return id != null && id.equals(appointment.id);
    }

    @Override
    public int hashCode() {
        return Appointment.class.hashCode();
    }

    @Override
    public String toString() {
        return "Appointment{" + appointmentNo + " " + appointmentDate + " "
                + appointmentTime + " " + status + "}";
    }
}
